name: "Build OI Notes"

on:
  push:
    branches:
      - main

jobs:
  build:
    name: "OI Notes Build"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout OI Notes"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: "Setup Python"
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
          cache: pipenv
      - name: "Setup Node.js"
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: "Install Python Dependencies"
        run: |
          curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python3
          pipenv install
      - name: "Cache Node.js Dependencies"
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: "Install Node.js Dependencies"
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: |
          npm --frozen-lockfile --production
      - name: "Install mkdocs-material"
        run: |
          pip install mkdocs-material
      - name: "Build OI Notes"
        run: |
          pipenv run mkdocs build
      - name: "Deploy OI Notes"
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          publish_branch: gh-pages
          cname: notes.shuzhouliu.bio
          keep_files: false
          user_name: shuzhouliu
          user_email: shuzhou.liu@hotmail.com